services:
    _defaults:
        public: false

    OAT\Library\HealthCheck\HealthChecker:
        arguments:
            - !tagged_iterator 'health_check.checker'

    OAT\Bundle\HealthCheckBundle\Action\HealthCheckAction:
        arguments: ['@OAT\Library\HealthCheck\HealthChecker']
        tags: ['controller.service_arguments']
