services:
    _defaults:
        public: false

    OAT\Library\HealthCheck\HealthChecker:
        arguments:
            - !tagged_iterator 'health_check.checker'
            - '@Psr\Log\LoggerInterface'

    OAT\Bundle\HealthCheckBundle\Action\HealthCheckAction:
        arguments: ['@OAT\Library\HealthCheck\HealthChecker']
        tags: ['controller.service_arguments']

    OAT\Bundle\HealthCheckBundle\Command\HealthCheckCommand:
        arguments: ['@OAT\Library\HealthCheck\HealthChecker']
        tags: ['console.command']
